version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - /home/minio/config:/root/.minio  #配置
      - /home/minio/data:/data           #数据
    ports:
      - "9090:9090"
      - "50000:50000"
    environment:
      - "MINIO_ACCESS_KEY=admin"
      - "MINIO_SECRET_KEY=admin1111"
    restart: always
    command: server /data --console-address ":50000" --address ":9090"